JdeRobot/drones

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
With this change, the take off height can be configurable. Closes #13
> Take off now is done by mixed control.

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
> Fixed bug on choosing takeoff height

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
> Swapped velocities at mixed control fixed

- drone_wrapper/scripts/play_python_code
- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
This PR includes:
- New velocity control (Vx Vy Vz YAW_RATE). This control masks a position control when speeds are zero and a mixed control when Vz is zero.
- Added position control (X Y Z YAW).
- Added mixed control (Vx Vy Z YAW_RATE).
- Takeoff now is quicker and done by height (previously was by vel/time).
- Script modified to allow passing arguments in launch file to python files.
> New control on drone wrapper

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
> Methods to get and set parameters implemented

- README.md
> Added all jenkins tags

- rqt_drone_teleop/src/rqt_drone_teleop/drone_teleop.py
> Added support to greyscale8 images

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
Now .get_landed_state() returns aicraft status (1: landed, 2: in the air...)
> Added method to get landed state

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
Now **.get_velocity()** returns the linear velocity components and **.get_yaw_rate()** the z component of the angular velocity, both extracted from the `/mavros/local_position/velocity_body` topic
> Added get_velocity() and get_yaw_rate()

- rqt_drone_teleop/src/rqt_pos_teleop/pos_teleop.py
- rqt_drone_teleop/src/rqt_vel_teleop/vel_teleop.py
> RQT freezing fixed

- rqt_drone_teleop/src/rqt_pos_teleop/pos_teleop.py
- rqt_drone_teleop/src/rqt_vel_teleop/vel_teleop.py
Synchronizing between vel and pose teleops. Closes #41.
Also fixes #21. Takeoff is only available when the drone is ready.
> Takeoff button synchro

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
> Fixing indentation

- rqt_drone_teleop/src/rqt_pos_teleop/pos_teleop.py
- rqt_drone_teleop/src/rqt_vel_teleop/vel_teleop.py
Might be improved using a ROS-based solution (#55).
Closes #62
> Freeze fixed using python threadings

- jderobot_drones/package.xml
> Added drone_assets dependency

- drone_assets/models/iris/iris.sdf
- drone_assets/models/iris_dual_cam/iris_dual_cam.sdf
- drone_assets/models/iris_red/iris_red.sdf
> Iris models updated

- rqt_drone_teleop/setup.py
Fixing jenkins-build fail. (#66)
> New setup.py

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
> Added namespace to topics and services

- drone_assets/CMakeLists.txt
> Added urdf as installed dir

- drone_wrapper/CMakeLists.txt
- drone_wrapper/package.xml
gazebo_ros was only used in roslaunch and forced to install gazebo 
Closes #81
> Removed unused dependency

- installation20.md
Added the installation20.md for ROS Noetic Ubuntu 20.04 (issue #80 )
> Add installation20.md

- drone_assets/CMakeLists.txt
- drone_assets/plugins/wall1.cc
- drone_assets/plugins/wall2.cc
- drone_assets/plugins/wall3.cc
- drone_assets/plugins/wall4.cc
fixes issue #90 
https://user-images.githubusercontent.com/40225765/116779527-44bc3980-aa94-11eb-94a4-f95475feed6c.mp4
Modified version of [this](https://github.com/JdeRobot/assets/tree/44ab9a73f359dfb78b5ab3f0e7f42d1ef85f8a36/jderobot_assets/plugins)
> [DroneHangar] Added plugins

- drone_assets/CMakeLists.txt
- drone_assets/package.xml
I am able to run `catkin_make` with no errors locally
> Fix issue-92

- installation20.md
> update installation20.md in master

- README.md
Fixes issue #92   
I am not sure if the Debian tags are necessary.
> Update README with new noetic branch

- drone_wrapper/src/drone_wrapper/__init__.py
> Fix import statement

- drone_assets/models/simple_labyrinth_green/model.config
- drone_assets/models/simple_labyrinth_green/model.sdf
> [noetic-devel] Added new simple_labyrinth_green

- drone_assets/models/simple_labyrinth_green/model.config
- drone_assets/models/simple_labyrinth_green/model.sdf
> [melodic-devel] Added new simple_labyrinth_green

- drone_assets/models/slab/model.config
- drone_assets/models/slab/model.sdf
> [noetic-devel] Added a new model slab

- drone_assets/models/slab/model.config
- drone_assets/models/slab/model.sdf
> [melodic-devel] Added a new model "slab"

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
- tello_driver/test/my_solution.py
> Cmd vel frame fixed and set to FLU

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
- tello_driver/test/my_solution.py
> [noetic] Cmd vel frame fixed and set to FLU

- drone_wrapper/launch/single_vehicle_spawn_sdf.launch
> Fix path mismatch

- drone_assets/models/custom_box_target_green/model.sdf
- drone_assets/models/custom_box_target_red/model.sdf
> [melodic-devel] Fixed path of custom_box_target

- drone_assets/models/custom_box_target_green/model.sdf
- drone_assets/models/custom_box_target_red/model.sdf
> [noetic-devel] Fixed path of custom_box_target

- README.md
> Fix broken link to installation guide

- drone_assets/package.xml
Adding gazebo_ros dependency to package.xml
Closes #141
> [melodic] Fix jenkins build on drone_assets package

- drone_assets/CMakeLists.txt
> Adding gazebo_ros dependency

- drone_wrapper/src/drone_wrapper/drone_wrapper_class.py
> Fixed string format error
